In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("cartera_crediticia.csv",parse_dates = ["fecha_originacion"])
data.head()

,prestamo_id,fecha_originacion,segmento,monto,plazo_meses,score_crediticio,ingreso_anual,dti,tasa_interes,default,perdida_dado_default
0,718802,2022-01-01,Retail,15216.79,36,588,41563.0,0.073,12.99,0,0.00
1,717632,2022-01-01,Retail,11099.15,36,702,63067.0,0.253,8.42,0,0.00
2,705403,2022-01-01,Retail,18965.70,36,618,35963.0,0.204,14.75,0,0.00
3,702284,2022-01-01,Retail,9615.90,60,671,69548.0,0.295,12.58,1,5267.01
4,719206,2022-01-01,Retail,4025.01,24,777,29543.0,0.045,8.13,0,0.00

In [6]:
data.info() #Te da un panorama interesante ... piensa en el caso donde donde en lugar de falso or true te den 0 ó 1  , o quizás, 1 o 2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   prestamo_id           20000 non-null  int64
 1   fecha_originacion     20000 non-null  datetime64[ns]
 2   segmento              20000 non-null  object
 3   monto                 20000 non-null  float64
 4   plazo_meses           20000 non-null  int64
 5   score_crediticio      20000 non-null  int64
 6   ingreso_anual         20000 non-null  float64
 7   dti                   20000 non-null  float64
 8   tasa_interes          20000 non-null  float64
 9   default               20000 non-null  int64
 10  perdida_dado_default  20000 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(4), object(1)
memory usage: 1.7+ MB

In [7]:
data.describe()

,prestamo_id,fecha_originacion,monto,plazo_meses,score_crediticio,ingreso_anual,dti,tasa_interes,default,perdida_dado_default
count,20000.000000,20000,2.000000e+04,20000.000000,20000.000000,2.000000e+04,20000.000000,20000.000000,20000.000000,2.000000e+04
mean,709999.500000,2023-07-02 15:09:04.320000256,1.576002e+05,47.506800,688.531950,1.838411e+05,0.198657,11.558882,0.157600,2.035075e+04
min,700000.000000,2022-01-01 00:00:00,1.154370e+03,12.000000,397.000000,5.439000e+03,0.020000,3.000000,0.000000,0.000000e+00
25%,704999.750000,2022-10-02 00:00:00,1.052417e+04,36.000000,639.000000,3.348550e+04,0.119000,9.130000,0.000000,0.000000e+00
50%,709999.500000,2023-07-01 00:00:00,1.930412e+04,48.000000,689.000000,5.707650e+04,0.195000,11.530000,0.000000,0.000000e+00
75%,714999.250000,2024-04-02 00:00:00,7.741118e+04,60.000000,739.000000,1.309260e+05,0.273000,13.940000,0.000000,0.000000e+00
max,719999.000000,2024-12-31 00:00:00,5.000000e+07,120.000000,850.000000,6.522654e+06,0.635000,25.530000,1.000000,1.056728e+07
std,5773.647028,NaN,7.079129e+05,25.003024,73.799035,4.127114e+05,0.107037,3.513548,0.364375,2.171885e+05